name: Continuous Integration (CI) for Build, Test, and Deploy

on:
  push:
    branches: [ main, develop, feature/ci-setup ]
  pull_request:
    branches: [ main, develop, feature/ci-setup ]
  workflow_dispatch:

jobs:
  buildTestDeploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses:  actions/checkout@v4

    - name: Set Up JDK 22
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Build with Gradle
      run: gradlew.bat clean build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: app/core/build/libs/**

    - name: Run Unit Test
      run: gradlew.bat test

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: app/core/build/reports/tests/**

    - name: Generate Code Coverage Report
      run: gradlew.bat jacocoTestReport

    - name: Upload code coverage report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: app/core/build/reports/jacoco/test/html/**

    #- name: Run Deployment
    #  run: java -jar build/libs/stirling-pdf-1.2.0.jar




